### ISSUE TITLE
CSS styles for kazari bar

### ISSUE THREAD

**Issue by dominv** [frees-io/freestyle-docs#23]
We need to create the CSS styles for the kazari bar:

![freestyle-doc-kazari](https://user-images.githubusercontent.com/3943031/28577844-32117e40-7158-11e7-883e-b24c25024564.png)

**Comment by israelperezglez** [comment]
Fixed in #22

**Comment by dominv** [comment]
Everything is working fine now. Thanks, @israelperezglez !!
